### ISSUE TITLE
Recommendation on building live / demo page?

### ISSUE THREAD

**Issue by JoshuaPerk** [labrodev/vuejs-embedded-widget#1]
Thanks for making this tutorial / library.

When I `yarn dev`, the index page is blank (I assume intentionally, since the desired state is actually the JS that is output during the build.

Do you have advice on how I can build locally with a demo page and live hot reloading?

**Comment by labrodev** [comment]
Hi!

Sorry for the delayed response! I hope you managed to solve your issue in the meantime. If not, I've prepared a solution in this commit:

https://github.com/labrodev/vuejs-embedded-widget/commit/2e06af811656b3f940aa1f5c9caf671b21ce2d75

The idea is that there is no way for us to treat the same solution and entry point of the application both for the widget-embedded solution and for its hot-key single-page reflection. The build-up is very different. For external usage, we wrap the application in a custom element to use in embedded mode (this happens in main.js). After the "build" command (npx vite build), the compiled script from the main.js entry point goes into /dist/widget.js, and we use it as a simple JS library like already compiled static code.

In your scenario (which is very useful), we just need to handle our code as a normal Vue.js single-page application (to use it in dev or preview mode). It's obvious that in a real project, there is a necessity to have this interpretation of the application because we need to develop, test, and fix without having to recompile and rebuild widget.js each time on an external site.

However, I have not found a brilliant solution to keep the same entry point (main.js) for both cases. Instead, here's what I've done:

Added dev.js where the entry point is organized like a standard Vue.js entry point.
Created Dev.vue as the root component for the application in "develop" or "preview" mode.
Made small adjustments in the root index.html to handle the application injected through dev.js + Dev.vue.
Updated vite.config.js with "preview" and "server" configurations to set up the entry point as "dev.js" instead of "main.js".
Now it will work in development and preview mode.

(Use "npm run dev" or "npx vite" to run it directly as a normal application).

All internal components remain the same; only the facade and entry point have changed.

Thank you for your question and good luck!

And of course I hope this solution will work with your yarn.
